config/routes.rb
Admintest::Application.routes.draw do
  resources :worker_profiles


  resources :worker_profiles
  resources :employer_profiles

  resources :pages


  resources :chapters


  resources :mangas


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  root :to => 'welcome#index'


end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
 attr_accessible :email, :password, :password_confirmation,
                   :remember_me
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  attr_accessible :chaptnum, :manga_id

  belongs_to :manga
  has_many :pages
end

app/models/employer_profile.rb
class EmployerProfile < ActiveRecord::Base
  has_one :user, as: :profile, dependent: :destroy
end

app/models/manga.rb
class Manga < ActiveRecord::Base
  attr_accessible :genre, :name

  has_many :chapters
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :chapter_id, :pagenum, :url

  belongs_to :chapter
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
         #:validatable
  attr_accessible :email, :password, :password_confirmation,
                    :remember_me
belongs_to :profile, polymorphic: true
end

app/models/worker_profile.rb
class WorkerProfile < ActiveRecord::Base
  attr_accessible :bio, :esl_level, :gender
  has_one :user, as: :profile, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chapters_controller.rb
class ChaptersController < InheritedResources::Base
end

app/controllers/mangas_controller.rb
class MangasController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
end

app/controllers/worker_profiles_controller.rb
class WorkerProfilesController < ApplicationController
  def new
    @worker_profile = WorkerProfile.new
  end

  def create
   @user = User.create(params[:user])
   @user.profile = WorkerProfile.create(params[:worker_profile])
   if @user.save
    redirect_to root_path
   else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/worker_profiles_helper.rb
module WorkerProfilesHelper
end

app/views/chapters/_form.html.haml
= form_for @chapter do |f|
  - if @chapter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@chapter.errors.count, "error")} prohibited this chapter from being saved:"
      %ul
        - @chapter.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :chaptnum
    = f.number_field :chaptnum
  .field
    = f.label :manga_id
    = f.number_field :manga_id
  .actions
    = f.submit 'Save'

app/views/chapters/edit.html.haml
%h1 Editing chapter

= render 'form'

= link_to 'Show', @chapter
\|
= link_to 'Back', chapters_path

app/views/chapters/index.html.haml
%h1 Listing chapters

%table
  %tr
    %th Chaptnum
    %th Manga
    %th
    %th
    %th

  - @chapters.each do |chapter|
    %tr
      %td= chapter.chaptnum
      %td= chapter.manga_id
      %td= link_to 'Show', chapter
      %td= link_to 'Edit', edit_chapter_path(chapter)
      %td= link_to 'Destroy', chapter, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Chapter', new_chapter_path

app/views/chapters/new.html.haml
%h1 New chapter

= render 'form'

= link_to 'Back', chapters_path

app/views/chapters/show.html.haml
%p#notice= notice

%p
  %b Chaptnum:
  = @chapter.chaptnum
%p
  %b Manga:
  = @chapter.manga_id

= link_to 'Edit', edit_chapter_path(@chapter)
\|
= link_to 'Back', chapters_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admintest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/mangas/_form.html.haml
= form_for @manga do |f|
  - if @manga.errors.any?
    #error_explanation
      %h2= "#{pluralize(@manga.errors.count, "error")} prohibited this manga from being saved:"
      %ul
        - @manga.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :genre
    = f.text_field :genre
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/mangas/edit.html.haml
%h1 Editing manga

= render 'form'

= link_to 'Show', @manga
\|
= link_to 'Back', mangas_path

app/views/mangas/index.html.haml
%h1 Listing mangas

%table
  %tr
    %th Genre
    %th Name
    %th
    %th
    %th

  - @mangas.each do |manga|
    %tr
      %td= manga.genre
      %td= manga.name
      %td= link_to 'Show', manga
      %td= link_to 'Edit', edit_manga_path(manga)
      %td= link_to 'Destroy', manga, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Manga', new_manga_path

app/views/mangas/new.html.haml
%h1 New manga

= render 'form'

= link_to 'Back', mangas_path

app/views/mangas/show.html.haml
%p#notice= notice

%p
  %b Genre:
  = @manga.genre
%p
  %b Name:
  = @manga.name

= link_to 'Edit', edit_manga_path(@manga)
\|
= link_to 'Back', mangas_path

app/views/pages/_form.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :pagenum
    = f.number_field :pagenum
  .field
    = f.label :chapter_id
    = f.number_field :chapter_id
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
%h1 Listing pages

%table
  %tr
    %th Pagenum
    %th Chapter
    %th Url
    %th
    %th
    %th

  - @pages.each do |page|
    %tr
      %td= page.pagenum
      %td= page.chapter_id
      %td= page.url
      %td= link_to 'Show', page
      %td= link_to 'Edit', edit_page_path(page)
      %td= link_to 'Destroy', page, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
%p#notice= notice

%p
  %b Pagenum:
  = @page.pagenum
%p
  %b Chapter:
  = @page.chapter_id
%p
  %b Url:
  = @page.url

= link_to 'Edit', edit_page_path(@page)
\|
= link_to 'Back', pages_path

app/views/worker_profiles/_form.html.haml
= form_for @worker_profile do |f|
  - if @worker_profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@worker_profile.errors.count, "error")} prohibited this worker_profile from being saved:"
      %ul
        - @worker_profile.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/worker_profiles/edit.html.haml
%h1 Editing worker_profile

= render 'form'

= link_to 'Show', @worker_profile
\|
= link_to 'Back', worker_profiles_path

app/views/worker_profiles/index.html.haml
%h1 Listing worker_profiles

%table
  %tr
    %th
    %th
    %th

  - @worker_profiles.each do |worker_profile|
    %tr
      %td= link_to 'Show', worker_profile
      %td= link_to 'Edit', edit_worker_profile_path(worker_profile)
      %td= link_to 'Destroy', worker_profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Worker profile', new_worker_profile_path

app/views/worker_profiles/new.html.erb
<h1>Sign Up</h1>

<%= form_for @worker_profile do |f| %>
  <% if @worker_profile.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @worker_profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag "user[email]", params[:user] %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag "user[password]", params[:password] %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %><br />
    <%= password_field_tag "user[password_confirmation]", params[:password_confirmation] %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :esl_level %><br />
    <%= f.text_field :esl_level %>
  </div>
  <div class="actions"><%= f.submit "Sign up" %></div>
<% end %>

app/views/worker_profiles/new.html.haml
%h1 New worker_profile

= render 'form'

= link_to 'Back', worker_profiles_path

app/views/worker_profiles/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_worker_profile_path(@worker_profile)
\|
= link_to 'Back', worker_profiles_path